version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - db
        container_name: recipes_api
        environment:
            - DEBUG=${DEBUG}
            - DJANGO_KEY=${DJANGO_KEY}
            - DB_HOST=db
            - DB_NAME=${POSTGRES_USERNAME}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres:13.2-alpine
        container_name: recipes_db
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USERNAME=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - recipes_db_data:/var/lib/postgresql/data

volumes:
    recipes_db_data: