version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # depends_on: postgres
        container_name: recipes_api
        environment:
            - DEBUG=${DEBUG}
            - DJANGO_KEY=${DJANGO_KEY}
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"