version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # depends_on: postgres
        container_name: recipes_api
        env_file:
            - ./.env
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"